# Generated by scripts/generate_build_info.sh. Do not edit by hand.
APP_VERSION = "0.3.12"
BUILD_NUMBER = "13"
GIT_COMMIT = "88069fb4"
BRAIN_VERSION = "0.3.12"
UPDATE_CHANNEL = "dev"
BUILD_DATE = "2026-06-26T23:27:21Z"
