#!/usr/bin/env bash
# Generate the single-source-of-truth build identity into both the Swift app
# and the Python brain. Reads repo-root VERSION / BUILD_NUMBER / UPDATE_CHANNEL
# (overridable via env), plus the current git commit and build date.
#
# Writes ONLY generated constant files:
#   Sources/JarvisCore/Generated/BuildInfo.swift   (enum JarvisBuildInfo)
#   brain/app/_build_constants.py                  (constants imported by build_info.py)
#
# Hand-written logic lives in AppVersionInfo.swift and build_info.py and is
# never overwritten here.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

read_or() { # file default
  local file="$ROOT/$1"
  if [ -f "$file" ]; then tr -d '[:space:]' < "$file"; else printf '%s' "$2"; fi
}

APP_VERSION="${JARVIS_VERSION:-$(read_or VERSION 0.0.0)}"
BUILD_NUMBER="${JARVIS_BUILD_NUMBER:-$(read_or BUILD_NUMBER 0)}"
UPDATE_CHANNEL="${JARVIS_UPDATE_CHANNEL:-$(read_or UPDATE_CHANNEL dev)}"
GIT_COMMIT="${JARVIS_GIT_COMMIT:-$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
BUILD_DATE="${JARVIS_BUILD_DATE:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
# The brain version tracks the app version: they ship together.
BRAIN_VERSION="$APP_VERSION"

echo "==> build identity"
echo "    appVersion=$APP_VERSION buildNumber=$BUILD_NUMBER channel=$UPDATE_CHANNEL commit=$GIT_COMMIT"

# --- Swift -----------------------------------------------------------------
SWIFT_DIR="$ROOT/Sources/JarvisCore/Generated"
mkdir -p "$SWIFT_DIR"
cat > "$SWIFT_DIR/BuildInfo.swift" <<EOF
// Generated by scripts/generate_build_info.sh. Do not edit by hand.
import Foundation

public enum JarvisBuildInfo {
    public static let appVersion = "$APP_VERSION"
    public static let buildNumber = "$BUILD_NUMBER"
    public static let gitCommit = "$GIT_COMMIT"
    public static let brainVersion = "$BRAIN_VERSION"
    public static let updateChannel = "$UPDATE_CHANNEL"
    public static let buildDate = "$BUILD_DATE"
}
EOF
echo "    wrote $SWIFT_DIR/BuildInfo.swift"

# --- Python ----------------------------------------------------------------
PY_FILE="$ROOT/brain/app/_build_constants.py"
cat > "$PY_FILE" <<EOF
# Generated by scripts/generate_build_info.sh. Do not edit by hand.
APP_VERSION = "$APP_VERSION"
BUILD_NUMBER = "$BUILD_NUMBER"
GIT_COMMIT = "$GIT_COMMIT"
BRAIN_VERSION = "$BRAIN_VERSION"
UPDATE_CHANNEL = "$UPDATE_CHANNEL"
BUILD_DATE = "$BUILD_DATE"
EOF
echo "    wrote $PY_FILE"
