from __future__ import annotations

from typing import Dict

from .mode import AssistantMode


def default_modes() -> Dict[str, AssistantMode]:
    modes = [
        AssistantMode(
            id="quick_assistant",
            name="Quick Assistant",
            purpose="Natural conversational assistant for the current Mac context.",
            trigger="Option+Space",
            execution_type="on_demand",
            default_model_route="gemini_fast",
            allowed_skills=["*"],
            context_policy={
                "active_app": True,
                "selected_text": True,
                "browser": True,
                "document": True,
                "calendar": True,
                "files": "approved_only",
                "memory": True,
            },
            response_style="short_natural",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "confirm_explicit"},
            max_response_length="short",
            speech_policy={"max_sentences": 1},
        ),
        AssistantMode(
            id="dictation",
            name="Dictation",
            purpose="Transcribe, clean, format, and insert spoken text without chatbot behavior.",
            trigger="Hold Fn or configured key",
            execution_type="on_demand",
            default_model_route="local_skill",
            allowed_skills=["dictation.clean", "dictation.format"],
            context_policy={"active_app": True, "selected_text": False, "memory": False},
            response_style="insert_only",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "blocked"},
            max_response_length="none",
            speech_policy={"speak": False},
        ),
        AssistantMode(
            id="email_writer",
            name="Email Writer",
            purpose="Draft and polish email replies using visible/current email context.",
            trigger="Mail/Gmail/Outlook context or email request",
            execution_type="on_demand",
            default_model_route="gemini_fast",
            allowed_skills=["email-draft-reply", "document-rewrite-selection"],
            context_policy={"email": "visible_current", "selected_text": True, "memory": True},
            response_style="draft_review",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "confirm_explicit"},
            max_response_length="medium",
            speech_policy={"max_sentences": 1},
        ),
        AssistantMode(
            id="document_editor",
            name="Document Editor",
            purpose="Rewrite, polish, summarize, and answer questions about selected/current document text.",
            trigger="Document editor context or selected text",
            execution_type="on_demand",
            default_model_route="gemini_fast",
            allowed_skills=["document-rewrite-selection", "document-summarize-current"],
            context_policy={"document": True, "selected_text": True, "browser": False},
            response_style="editing_direct",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "confirm_explicit"},
            max_response_length="medium",
            speech_policy={"max_sentences": 1},
        ),
        AssistantMode(
            id="daily_brief",
            name="Daily Brief",
            purpose="Opt-in scheduled summary from enabled calendar, reminder, email, and task sources.",
            trigger="Scheduled opt-in",
            execution_type="scheduled",
            default_model_route="gemini_fast",
            allowed_skills=["calendar-today", "files-search"],
            context_policy={"connectors": "enabled_only", "background_scraping": False},
            response_style="briefing",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "blocked"},
            max_response_length="short",
            speech_policy={"max_sentences": 4},
        ),
        AssistantMode(
            id="deep_research",
            name="Deep Research",
            purpose="Longer on-demand research using files, web, notes, and citations.",
            trigger="Explicit research request",
            execution_type="on_demand",
            default_model_route="gemini_smart",
            allowed_skills=["files-search", "files-summarize", "document-summarize-current"],
            context_policy={"files": "approved_only", "web": "enabled_only", "citations": True},
            response_style="sourced",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "confirm_explicit"},
            max_response_length="long",
            speech_policy={"summary_only": True},
        ),
        AssistantMode(
            id="code_helper",
            name="Code Helper",
            purpose="Read approved project files, reason about code, and propose changes.",
            trigger="Explicit coding request",
            execution_type="on_demand",
            default_model_route="gemini_smart",
            allowed_skills=["files-search", "files-summarize"],
            context_policy={"files": "approved_project_only", "shell": "confirm"},
            response_style="engineering",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "confirm_explicit"},
            max_response_length="long",
            speech_policy={"summary_only": True},
        ),
        AssistantMode(
            id="focus_monitor",
            name="Focus Monitor",
            purpose="Continuous monitoring only for explicitly enabled user-approved conditions.",
            trigger="Explicit opt-in",
            execution_type="continuous",
            default_model_route="local_small",
            allowed_skills=[],
            context_policy={"continuous_indicator": True, "enabled_by_default": False},
            response_style="quiet_status",
            risk_policy={"green": "auto", "yellow": "confirm", "red": "blocked"},
            max_response_length="short",
            speech_policy={"speak": False},
        ),
        AssistantMode(
            id="skill_learning",
            name="Skill Learning",
            purpose="Turn repeated workflows, notes, docs, or traces into staged reusable skills.",
            trigger="learn this / make this a skill / save this workflow",
            execution_type="on_demand",
            default_model_route="gemini_smart",
            allowed_skills=["jarvis-learn-skill"],
            context_policy={"conversation": True, "selected_text": True, "private_content": "explicit_only"},
            response_style="approval_first",
            risk_policy={"green": "stage", "yellow": "stage", "red": "blocked"},
            max_response_length="medium",
            speech_policy={"max_sentences": 1},
        ),
    ]
    return {mode.id: mode for mode in modes}
